In [15]:
import pandas as pd 
import numpy as np

cd = pd.read_csv(r"C:\Users\lenovo\Desktop\Downloads\Data\Close_Date data.csv")

In [3]:
cd

,Zone,Site Address,Region,Opportunity ID,Opp Created On,Enquiry Created By,Customer Name,Contact Number,E-Mail,City,...,Gross Value,Net Value,Basic Value (at DP),Standard Discount,1st Discount Given,Closed Customer value,Closed Basic value,MSC Material value,MSC Gross Value,Lost Price
0,Bangalore,"""Channabasava"", 1st cross, near Mission compou...",UPC BLR 2,549010,21.05.2022,Dealer,Prabhudeva Hanji,+91 9480318474,prabhudevahanji@gmail.com,Shivamogga,...,"146,526.98 INR","119,088.69 INR","107,179.82 INR",0.00 INR,0.00 INR,0.00 INR,0.00 INR,0.00 INR,0,0
1,Bangalore,"# 108-F9, 6th cross, 2nd main, HGH layout / Ba...",Bangalore City,538773,23.04.2022,Dealer,Narayana Rao,+91 7676443655,narayana.r0@pragathi.biz,Bangalore,...,"1,936,637.20 INR","1,593,551.21 INR","1,166,320.12 INR",0.00 INR,0.00 INR,0.00 INR,0.00 INR,0.00 INR,0,"500,000.00 INR"
2,Bangalore,"# 3A Fair Field Appt,Benson Town / Banglore 56...",Bangalore City,550761,26.05.2022,Dealer,Mr Vikram,+91 9987023229,vadige.@gmail.com,Banglore,...,"1,296,645.65 INR","1,077,649.64 INR","788,731.78 INR",0.00 INR,0,0.00 INR,0.00 INR,0.00 INR,0,0
3,Bangalore,# 607 16th D ain Benaka Towers Kodihalli. / Ba...,Bangalore City,555286,06.06.2022,Sales,Sajan Hegde,+91 9987115499,roopasharma22@gmail.com,Bangalore,...,"146,411.38 INR","118,024.77 INR","110,746.58 INR","33,289.04 INR",0.00 INR,"146,411.38 INR","118,024.77 INR","94,134.59 INR","100,187.26 INR",0
4,Bangalore,"# G14 DC Capital,kadubeesanahalli / Banglore 5...",Bangalore City,563153,24.06.2022,Dealer,Mr Aditya Kolli,+91 8142380196,kolliaaditya@gmail.com,Banglore,...,"90,759.49 INR","75,077.11 INR","54,948.94 INR",0.00 INR,0,0.00 INR,0.00 INR,0.00 INR,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10147,Not assigned,Village Hyatpur Rurki / Navashehar 144532 / IN,#,512479,14.02.2022,Connect Center,Amarjit Singh,+91 8847569067,Sarvjitkaur_kaur2132@yahoo.com,Navashehar,...,0,0,0,0,0.00 INR,0,0,0,0,0
10148,Not assigned,"Vipanchika house ,SN Junction / Trippunithura ...",#,533232,07.04.2022,Connect Center,Dr Sreejith S,+91 9400626123,drsreeje@gmail.com,Trippunithura,...,0,0,0,0,0.00 INR,0,0,0,0,0
10149,Not assigned,collecterate road / Rewa 486001 / IN,#,552356,30.05.2022,Connect Center,Mohd Ishtiyaq,+91 9425841888,ishtiyaq.rewa@gmail.com,Rewa,...,0,0,0,0,0.00 INR,0,0,0,0,0
10150,Not assigned,karnal 132001 / IN,#,563350,24.06.2022,Sales,The Design Room,+91 9518069000,veekayguru@gmail.com,karnal,...,"169,962.29 INR","137,901.10 INR","124,110.99 INR","18,804.70 INR",0.00 INR,0.00 INR,0.00 INR,0.00 INR,0,0
10151,Not assigned,satna 485001 / IN,#,396128,19.03.2021,#,Himansh Manghnani,+91 8878886488,himanshumanghnani01@gmail.com,satna,...,0,0,0,0,0.00 INR,0,0,0,0,0

In [4]:
cd.shape

(10152, 63)

In [5]:
cd.size

639576

In [9]:
cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10152 entries, 0 to 10151
Data columns (total 63 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Zone                              10152 non-null  object
 1   Site Address                      10152 non-null  object
 2   Region                            10152 non-null  object
 3   Opportunity ID                    10152 non-null  int64
 4   Opp Created On                    10152 non-null  object
 5   Enquiry Created By                10152 non-null  object
 6   Customer Name                     10152 non-null  object
 7   Contact Number                    10152 non-null  object
 8   E-Mail                            10152 non-null  object
 9   City                              10152 non-null  object
 10  State                             10152 non-null  object
 11  Pincode                           10152 non-null  int64
 12  Source of Enq                     10152 non-null  object
 13  Sales Owner                       10152 non-null  object
 14  Sales Owner ID                    10152 non-null  object
 15  CSE Name                          10152 non-null  object
 16  Nature of Work                    10152 non-null  object
 17  Influencer Involved               10152 non-null  object
 18  Influencer Name                   10152 non-null  object
 19  First Interaction Date            10152 non-null  object
 20  Site Visit Date                   10152 non-null  object
 21  Persuasion Date                   10152 non-null  object
 22  Showroom Visit Date               10152 non-null  object
 23  Boq Received Date                 10152 non-null  object
 24  Product Category                  10152 non-null  object
 25  Client expectation Price Bracket  10152 non-null  object
 26  Quote Segment                     10152 non-null  object
 27  WM Order Type                     10152 non-null  object
 28  WM Quote ID                       10152 non-null  object
 29  First Quote Date                  10152 non-null  object
 30  Latest Quote Date                 10152 non-null  object
 31  Quote Review Date                 10152 non-null  object
 32  Expected Closure Month            10152 non-null  int64
 33  No. of Sales Quote                10152 non-null  int64
 34  Won/Lost/In Process               10152 non-null  object
 35  Last Progression Stage            10152 non-null  object
 36  Order in Hand                     10152 non-null  object
 37  Order in Hand Date                10152 non-null  object
 38  Status-Hot / Warm/ Cold           10152 non-null  object
 39  Remarks                           10145 non-null  object
 40  Main Competitor                   10152 non-null  object
 41  Reason for Status                 10152 non-null  object
 42  Expected Site Readiness Date      10152 non-null  object
 43  1st Discount Given Date           10152 non-null  object
 44  2nd Discount Given Date           10152 non-null  object
 45  Order Basis to Fenesta            10152 non-null  object
 46  Quote Area                        10152 non-null  object
 47  Next Step                         10138 non-null  object
 48  Next Step Due Date                10152 non-null  object
 49  Window Quantity                   10152 non-null  object
 50  Window Area(Taken from Customer)  10152 non-null  object
 51  Expected Value                    10152 non-null  object
 52  Quote Value                       10152 non-null  object
 53  Gross Value                       10152 non-null  object
 54  Net Value                         10152 non-null  object
 55  Basic Value (at DP)               10152 non-null  object
 56  Standard Discount                 10152 non-null  object
 57  1st Discount Given                10152 non-null  object
 58  Closed Customer value             10152 non-null  object
 59  Closed Basic value                10152 non-null  object
 60  MSC Material value                10152 non-null  object
 61  MSC Gross Value                   10152 non-null  object
 62  Lost Price                        10152 non-null  object
dtypes: int64(4), object(59)
memory usage: 4.9+ MB

In [11]:
cd.isna().sum()

Zone                     0
Site Address             0
Region                   0
Opportunity ID           0
Opp Created On           0
                        ..
Closed Customer value    0
Closed Basic value       0
MSC Material value       0
MSC Gross Value          0
Lost Price               0
Length: 63, dtype: int64

In [18]:
cd.nunique()

Zone                        11
Site Address              9261
Region                      62
Opportunity ID           10152
Opp Created On             671
                         ...
Closed Customer value     1244
Closed Basic value        1244
MSC Material value        1062
MSC Gross Value           1061
Lost Price                 147
Length: 63, dtype: int64

In [19]:
cd.ndim

2